plugins:
  lottery_v2_enabled:
    default: false
    client: false
  lottery_v2_trigger_categories:
    default: ""
    client: false
    type: "string"
  lottery_v2_trigger_tags:
    default: ""
    client: false
    type: "string"
  lottery_v2_floor_fallback:
    default: "void"
    client: false
    type: "enum"
    choices:
      - void
      - next
  lottery_v2_max_winners:
    default: 50
    client: false
    type: "integer"
    min: 1
    max: 100
  lottery_v2_min_participants:
    default: 2
    client: false
    type: "integer"
    min: 1
  lottery_v2_auto_close_topic:
    default: true
    client: false
    type: "bool"
  lottery_v2_send_notifications:
    default: true
    client: false
    type: "bool"
  lottery_v2_cache_duration:
    default: 60
    client: false
    type: "integer"
    description: "Duration in seconds for caching participant count."
    min: 30
    max: 3600
  lottery_v2_allowed_trust_levels:
    default: "1|2|3|4"
    client: false
    type: "list"
    list_type: "integer"
  lottery_v2_max_future_days:
    default: 365
    client: false
    type: "integer"
    min: 1
    max: 3650
